# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'EVSample' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
pod 'JKBigInteger', '~> 0.0.1'
end
